services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
      args:
        DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    image: til-next-test
    container_name: lyzgame-web
    environment:
      - HOSTNAME=0.0.0.0
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    ports:
      - "3004:3000"
    restart: always
    depends_on:
      - db
    command: >
      sh -c "npx prisma migrate deploy && node node_modules/next/dist/bin/next start -p 3000"
  db:
    container_name: lyzgame-db
    image: postgres:latest 
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
volumes:
  db-data:
